package com.doremitutor.persistence;

import java.io.Serializable;

public final class Constants implements Serializable{
	private Constants(){assert false:"Monostate case";}
	public enum Rhythm{WHOLE_DOTTED, WHOLE,
			HALF_DOUBLE_DOTTED, HALF_DOTTED, HALF,
			QUARTER_DOUBLE_DOTTED, QUARTER_DOTTED, QUARTER, QUARTER_TRIPLET,
			EIGHT_DOTTED, EIGHT, EIGHT_TRIPLET,
			SIXTEENTH, SIXTEENTH_TRIPLET}
	public enum Pitch{B1FLAT, B1, B1SHARP,
			C2FLAT, C2, C2SHARP, D2FLAT, D2, D2SHARP, E2FLAT, E2, E2SHARP, F2FLAT, F2, F2SHARP,
			G2FLAT, G2, G2SHARP, A2FLAT, A2, A2SHARP, B2FLAT, B2, B2SHARP,
			C3FLAT, C3, C3SHARP, D3FLAT, D3, D3SHARP, E3FLAT, E3, E3SHARP, F3FLAT, F3, F3SHARP,
			G3FLAT, G3, G3SHARP, A3FLAT, A3, A3SHARP, B3FLAT, B3, B3SHARP,
			C4FLAT, C4, C4SHARP, D4FLAT, D4, D4SHARP, E4FLAT, E4, E4SHARP, F4FLAT, F4, F4SHARP,
			G4FLAT, G4, G4SHARP, A4FLAT, A4, A4SHARP, B4FLAT, B4, B4SHARP,
			C5FLAT, C5, C5SHARP, D5FLAT, D5, D5SHARP, E5FLAT, E5, E5SHARP, F5FLAT, F5, F5SHARP,
			G5FLAT, G5, G5SHARP, A5FLAT, A5, A5SHARP, B5FLAT, B5, B5SHARP,
			C6FLAT, C6, C6SHARP, D6FLAT, D6, D6SHARP}
	public enum Cleff{TREBLE, BASS}
	public enum Time{T24, T34, T44, T22, T38, T68, T98, T128}
}